### ISSUE TITLE
Création des maquettes graphiques

### ISSUE THREAD

**Issue by Astroop** [Ludoutt/GroupeB#1]

**Comment by Astroop** [comment]
Créer les première maquettes pour que le user puisse se connecter et accéder a son dashboard avec ses backlogs

**Comment by eva974** [comment]
Maquette : 
https://xd.adobe.com/view/62ecc243-9899-4718-6675-bad1a348011e-14dd/

**Comment by chloebr** [comment]
User story :
En tant que **utilisateur de l'application**, je peux **naviguer facilement** à travers cette dernière dans le but de **me concentrer sur le contenu et pas sur le contenant**.
